### PR TITLE
Fix Unfurling darkness again (again [again] )

### LINKED ISSUE #4655: [BUG] Shadowpriest Voidweaver - Working well wenn suddenly the addon wants me spam Vampiric Touch for no reason, game restart fixes this
### Before You Begin

- [x] I confirm that I have downloaded the latest version of the addon.
- [x] I am not playing on a private server.
- [x] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [x] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [x] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Priest - Shadow

### Describe the Issue

Im doing mythic + dungeons and everything is working great. and randomly, not at a specific time, or atleast i dont know how to reconstruct the bug, the addon wants me to spam vampiric touch, without unfurling darkness ready, every enemy having Vampiric Touch on them without falling off soon, 2 stacks of Vampiric Blast.
the only thing fixing this for me was restarting the game, not even reloading works.

I have this problem only as Voidweaver, not happening on Archon Hero Tree. It might be an issue with Unfurling Darkness maybe or mind spike? those are the two talents i dont play on Archon but do so on Voidweaver

### How to Reproduce

1. Enter the game as Shadow Priest
2. Change ur Talents to this 

Image

3. Play the rotation, at best in mythic plus, will happen eventually. happened to me in every m+ i did so far.

### Snapshot (Link)

https://pastebin.com/nYLyVEnX

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/f65GYW7NpyCH9Y8HwuKfFr 

### Additional Information

https://www.raidbots.com/simbot/report/6UoxDiwpDVyj8qFMJzo4BC

https://www.raidbots.com/simbot/report/78dvRmcQp4KC3y2HYWR9m5

Paste bin for AOE: https://pastebin.com/enrnUt6S
it created 2 Snapshots, i guess because i Play on Dual mode

### Contact Information

_No response_

### PR DESCRIPTION
**Pull request by syrifgit**
Added new state function to sync the `buff.unfurling_darkness_cd` with the player debuff using `state.auras.player.debuff.unfurling_darkness_cd`. Tested in game, the "buff" finally stays synced.

Fixes https://github.com/Hekili/hekili/issues/4655

### CODE REVIEW

File: TheWarWithin/PriestShadow.lua [hunk 1]
```diff
@@ -1019,7 +1019,7 @@ spec:RegisterHook( "reset_precast", function ()
         applyBuff( "shadowform" )
     end
 
-    if debuff.unfurling_darkness_cd.up then applyBuff( "unfurling_darkness_cd", debuff.unfurling_darkness_cd.remains ) end
+    applyBuff( "unfurling_darkness_cd", state.PlayerDebuffRemains( "unfurling_darkness_cd" ) )
```
Comment (Hekili) [inline TheWarWithin/PriestShadow.lua:1022]: I *guess* this is OK, but you're adding to the mess of functions that I don't really want to exist in the first place.

**Review by Hekili — APPROVED** [review]
