### PR TITLE
Enhance Pack String, all 3 shaman specs swiftness fixes

### LINKED ISSUE #3869: [REC] Casting any spell with cast time will prevent Ancestral Swiftness recommendation until end of current cast.
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Elemental

### Describe the Issue

Casting any spell with cast time will prevent Ancestral Swiftness recommendation until end of current cast.
Looking at snapshots it seems like Hekili is putting Ancestral Swiftness on cooldown whenever player is casting spell that has cast time

### How to Reproduce

1. Enter game as Elemental shaman
2. Use Single Target build from wowhear (Farseer)
3. When Hekili will suggest Ancestral Swiftness start casting spell that has cast time
4. Ancestral Swiftness icon will disappear until you finish your cast

### Snapshot (Link)

Snapshot when not casting
https://pastebin.com/DaVi9MsQ

Snapshot when casting Lightning Bolt and Ancestral Swiftnes is ready to use 
https://pastebin.com/kNgE6sfu

### Raidbots Sim Report (Link)

_No response_

### Additional Information

_No response_

### Contact Information

_No response_

### PR DESCRIPTION
**Pull request by syrifgit**
fixes 
#3869 
#3867 

These buffs were triggering their cooldown on spellcast due to the onRemove function of the aura being triggered any time the spell was cast

Adding a check to only remove buff if buff is up fixes this behaviour.

### CODE REVIEW

File: TheWarWithin/ShamanEnhancement.lua [hunk 1]
```diff
@@ -2741,4 +2742,4 @@ spec:RegisterSetting( "filler_shock", true, {
...
...D57u)mTeDA(Ee3biMDS7dzh9qu)GOBcYn2k3fyg3y67dvP947BPhK2BhPLuTwxomvU6jM40Eqz2jlWMVjSTq(WkIy1KQDRCqJkxCtlggeZtyxayXAB1(GYicTApgpTMUAvWU46uIx7MTc991prSuaM7n14zLfiij2X6xO67w9a(XFUneX9Nw1S8bzYmxLxyvEx4SSjUkXCDGA4G4(1GKb6GVuyhayqTDR9lf)ra1CtF)TyIa(CktBtmFcq)i1O3y3zJPn)34po1GoOjIaql6JelhnyhdwX1KnUNfwbzCs0S97dRBO1)wbcOpTlrciU2n1(j75Qqwg1WYSGlIbz1l1Gwd46cRVTvdJ8cTlsO049DFaMp)Ei08RvP5d6HmTl1Xg9Awbi64UEXvkdQ6kO2u0)fBP1fAJVn6jJAtyhn82My8TuPGQ0qNjvsxI8dyTkhmWA3BBHqRD7g6wbOvdzFP)7hiQVBWhBa(ynjC0cdMS9vREmCroZx)ERNUNDjjydINz)GHlrKT((wryCh9WSljic8q0QK0kZQwSlH7k0vi27SfoNPMWxrW8WmJb0AO8vux144ThojCa(AmCJDqnkn74VzkoMlcKbkPFjqE9vWabhi8Ey4DqimI4xzaQxcLFTpAVtIwisR0T3kkSALyquPfOPRIVY)EJmVKmEz5NQdtJL7CKB8Ta63KdJW2UapovlejCLgufuhy1EXh9(i4WLLJX7UpvGOxCwIeqZCNGzNtoJo(XJ8m5dSkWGivQDpZrAWbQxcaGTREdUcx5nifubed0qbyLRFSZmcUf)ospcGCS7DlYPLb42j1kwr1AdCoFomAP4O7BEPWVXCmX9MgIGPBKrsV8id21QR7DkyneA5yeD0z4UkxwLR87sYgtSCfK8IERx1gtIqPncu0cce(OKOSnDKU0hkdW0USkhykRaifCkHIHHYkumiyWIhpNkQh(NkxdMTmM3l5NYsczxHuc8eL(y5sc1IF4Pirse(nwxs4PaYLwoYKXDQEVUw)U2q1baAqBWpkLhOzLq71tpBYOx7sgfI8EmQbrJYO7y93RYqCZm1Kib26Jr2(n4XHNWVjbgAFoS0(bxNFMZ8FxeKus(3UjDZKNlBt6)TZwH9892Zm4bYCYoYAvJWwOuUrY9L949tziiwI889Wvoc4SlERz5D(U5qggbCwrcmtXOfLG97H5D)N]] )
```
Comment (Hekili) [inline TheWarWithin/ShamanEnhancement.lua:2745]: Was there a revision to the Enhancement priority?  If so, the text version needs to be updated.

Comment (syrifgit) [reply TheWarWithin/ShamanEnhancement.lua:2745]: Ticket https://github.com/Hekili/hekili/issues/3867 claims that the .simc file was updated in the addon, but the pack string is the same as it was before those changes. If that's not true I can withdraw that part from the PR.

This pack string is me importing the .simc file contents directly from Hekili github and then exporting as a string.
