### PR TITLE
Align all 3 DK specs rune definitions

### LINKED ISSUE #4379: UH: Death Coil issue again
### Before You Begin

- [x] I confirm that I have downloaded the latest version of the addon.
- [x] I am not playing on a private server.
- [x] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [x] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

M+, Not sure what happenend, auto snap shotted.  Caputred.

### How to Reproduce

Not sure how to reproduce, may again my mistake in game play, but, maybe not.  

### Player Information (Link)

https://pastebin.com/UkD6Tv33

### Error Messages (Link)

https://pastebin.com/UkD6Tv33

### Additional Information

Here is teh screenshot as well.

Image

### Contact Information

Wren#1740

### PR DESCRIPTION
**Pull request by syrifgit**
- Nil protections were missing from Frost and Unholy `reset` function
  - Fixes #4379
- Update Blood expiry table stuff to match the newer version in UH/Frost
- Changed formatting / declaration order of model to be identical between the 3, no functional change
- Simplify some wordy comments, removed duplicated ones, whitespace stuff, etc.

### CODE REVIEW

File: TheWarWithin/DeathKnightBlood.lua [hunk 1]
```diff
@@ -47,51 +47,45 @@ spec:RegisterResource( Enum.PowerType.Runes, {
...
-
         for i = 1, amount do
-            t.expiry[ 7 - i ] = 0
+            table.insert( t.expiry, 0 )
+            t.expiry[ 7 ] = nil
         end
         table.sort( t.expiry )
-
-        t.actual = nil
+        t.actual = nil -- Reset actual to force recalculation
```
Comment (bjth) [inline TheWarWithin/DeathKnightBlood.lua]: Comment got added here, but taken out of the other places, want to be consistent and remove it?

Comment (syrifgit) [reply TheWarWithin/DeathKnightBlood.lua]: Imagine being consistent, couldn't be me
