### PR TITLE
Fix #4839 - make Coup de Grace "known" Fix for #4840 - adjust rtb_primary_remains calculation

### LINKED ISSUE #4839: Coup de Grace abbillity is unpredictable
### Before You Begin

- [x] I confirm that I have downloaded the latest version of the addon.
- [x] I am not playing on a private server.
- [x] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [x] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [x] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Outlaw

### Describe the Issue

The Coup de Grace ability remains unknown until we reach 4 stacks of Escalating Blade, which makes it impossible to queue this ability as Recommendation 2 or 3. As a result, it suddenly appears as Recommendation 1—despite the fact that we can predict when 4 stacks will be reached based on the number of casts of Sinister Strike or Ambush.

For the purpose of tracking this bug, I added Unseen Blade tracking. No other code was changed. (Here is the commit.)  https://github.com/Hekili/hekili/compare/thewarwithin...IIeTpoc:hekili:thewarwithin

Snapshot 1: https://pastebin.com/MJUusJJK
Cout de Grace (CdG) is unknown.
We have 3 stacks of Escalating Blade (EB) and next Sinister Strike (SS) will make CdG available as it will grand +1 stack of EB for sure due to Disorenting Strikes (DS) are up .

Snapshot 2: https://pastebin.com/h0NdfuHY
Was  taken right after pressing SS after Snapshot 1 was made.
As we can see, the Recommendation 1 is CdG, which corresponds with the current APL.

### How to Reproduce

1. Get 3 Stacks of EB
2. Use Killing Spree
3. Look at Rec. 1,2,3 etc. You will not see CdG
4. Use 1 SS
5. After SS the next abbility as Rec 1 will suddenly appear as CdG

### Snapshot (Link)

Snapshot 1: https://pastebin.com/MJUusJJK, Snapshot 2: https://pastebin.com/h0NdfuHY

### Raidbots Sim Report (Link)

_No response_

### Additional Information

_No response_

### Contact Information

IIeTpoc#2324

### PR DESCRIPTION
**Pull request by IIeTpoc**
Fix #4839 - make Coup de Grace "known" 
Fix for #4840
Now container calculations (rtb_primary_remains) are triggered by rtb_cast.
For me after several tests it fixed the issue.
https://pastebin.com/fXRkPvX7
https://pastebin.com/Fn7Fnnrv

Add Unseen Blade to a snapshot.

### CODE REVIEW

File: TheWarWithin/RogueOutlaw.lua [hunk 1]
```diff
@@ -636,8 +645,9 @@ local TriggerUnseenBlade = setfenv( function( )
 end, state )
 
 spec:RegisterStateExpr( "rtb_primary_remains", function ()
-    local baseTime = max( lastRoll or 0, action.roll_the_bones.lastCast or 0 )
-    return max( 0, baseTime + rollDuration - query_time )
+  --  local baseTime = max( lastRoll or 0, action.roll_the_bones.lastCast or 0 )
+  --  return max( 0, baseTime + rollDuration - query_time )
+    return max( 0, ( lastRoll or 0 ) + rollDuration - query_time )
```
Comment (Hekili) [inline TheWarWithin/RogueOutlaw.lua]: We have to use `action.roll_the_bones.lastCast` so that the queue stays sane after recommending RtB.

File: TheWarWithin/RogueOutlaw.lua [hunk 2]
```diff
@@ -1215,6 +1238,7 @@ spec:RegisterAbilities( {
         cooldown = 0,
         gcd = "totem",
         school = "physical",
+        known    = 2098,
```
Comment (Hekili) [inline TheWarWithin/RogueOutlaw.lua]: Fix spaces.

**Review by Hekili — CHANGES_REQUESTED** [review]
Fix spacing and use of action.roll_the_bones.lastCast.

File: TheWarWithin/RogueOutlaw.lua (hunk 1 above)
Comment (IIeTpoc) [reply TheWarWithin/RogueOutlaw.lua]: Resolved

File: TheWarWithin/RogueOutlaw.lua (hunk 2 above)
Comment (IIeTpoc) [reply TheWarWithin/RogueOutlaw.lua]: Resolved

**Review by IIeTpoc — COMMENTED** [review]
It should be resolved

**Review by Hekili — APPROVED** [review]
